SAMPLES:
 - 20210720_RNAseq_oeHNRNPK_Rep1
 - 20210720_RNAseq_oeHNRNPK_Rep2
 - 20210720_RNAseq_oeNC_Rep1
 - 20210720_RNAseq_oeNC_Rep2
 - 20210720_circRNAseq_oeHNRNPK_Rep1
 - 20210720_circRNAseq_oeHNRNPK_Rep2
 - 20210720_circRNAseq_oeNC_Rep1
 - 20210720_circRNAseq_oeNC_Rep2
FASTA: ../common/ucsc_hg38/hg38.fa
GTF: ../common/ucsc_hg38/knownGene.gtf
GENEPRED: ../common/ucsc_hg38/refFlat.txt
RIBOSOME: /home/zgchen/species/homo_sapiens/ncbi/ribosomal_rna.fasta
