SAMPLES:
 - 20241028_293T_HNRNPK_CLIP_IP_Rep1
 - 20241028_293T_HNRNPK_CLIP_IP_Rep2
 - 20241028_293T_HNRNPK_CLIP_Input_Rep1
 - 20241028_293T_HNRNPK_CLIP_Input_Rep2
 - 20241028_293T_RBM12_CLIP_IP_Rep1
 - 20241028_293T_RBM12_CLIP_IP_Rep2
 - 20241028_293T_RBM12_CLIP_Input_Rep1
 - 20241028_293T_RBM12_CLIP_Input_Rep2
GENOME_FASTA: ../common/ucsc_hg38/hg38.fa
GENOME_SIZES: ../common/ucsc_hg38/hg38.sizes
BOWTIE2_RIBO_INDEX: ../1_circRNAseq/results/1_prepare/2_index/ribo_index
STAR_REP_INDEX: ../common/star_humrep
STAR_GENOME_INDEX: ../common/star_hg38_index
